var filename='client/views/editor/aceedit/aceEditTexNotations.js';

AceEditTextNotations = {
	// Greek Letters
	alpha 		: 	{ tex : 'alpha', alias : ['alpha'] },              
	theta 		: 	{ tex : 'theta', alias : ['theta'] }, 
	o 	  		: 	{ tex : 'o', alias : ['o'] },
	tau			: 	{ tex : 'tau', alias : ['tau'] },          
	beta		: 	{ tex : 'beta', alias : ['beta'] },
	vartheta	: 	{ tex : 'vartheta', alias : ['vartheta'] },            
	pi			: 	{ tex : 'pi', alias : ['pi'] },                  
	upsilon		: 	{ tex : 'upsilon' , alias : ['upsilon']},       
	gamma		: 	{ tex : 'gamma', alias : ['gamma'] },              
	varpi		: 	{ tex : 'varpi', alias : ['varpi'] },              
	phi			: 	{ tex : 'phi', alias : ['phi'] },          
	delta		: 	{ tex : 'delta', alias : ['delta'] },                
	kappa		: 	{ tex : 'kappa', alias : ['kappa'] },              
	rho			: 	{ tex : 'rho', alias : ['rho'] },                
	varphi		: 	{ tex : 'varphi', alias : ['varphi'] },        
	epsilon		: 	{ tex : 'epsilon', alias : ['epsilon'] },              
	lambda		: 	{ tex : 'lambda', alias : ['lambda'] },             
	varrho		: 	{ tex : 'varrho', alias : ['varrho'] },              
	chi			: 	{ tex : 'chi', alias : ['chi'] },           
	varepsilon	: 	{ tex : 'varepsilon', alias : ['varepsilon'] },          
	mu			: 	{ tex : 'mu', alias : ['mu'] },                  
	sigma		: 	{ tex : 'sigma', alias : ['sigma'] },              
	psi			: 	{ tex : 'psi', alias : ['psi'] },           
	zeta		: 	{ tex : 'zeta', alias : ['zeta'] },                 
	nu			: 	{ tex : 'nu', alias : ['nu'] },                 
	varsigma	: 	{ tex : 'varsigma', alias : ['varsigma']  },          
	omega		: 	{ tex : 'omega', alias : ['omega']},        
	eta			: 	{ tex : 'eta', alias : ['eta'] },                 
	xi			: 	{ tex : 'xi', alias : ['xi'] },                                            
	                                                                 
	Gamma		: 	{ tex : 'Gamma', alias : ['Gamma'] },                
	Lambda		: 	{ tex : 'Lambda', alias : ['Lambda'] },             
	Sigma		: 	{ tex : 'Sigma', alias : ['Sigma'] },              
	Psi			: 	{ tex : 'Psi', alias : ['Psi'] },          
	Delta		: 	{ tex : 'Delta', alias : ['Delta'] },               
	Xi 			: 	{ tex : 'Xi', alias : ['Xi'] },                 
	Upsilon		: 	{ tex : 'Upsilon', alias : ['Upsilon'] },            
	Omega		: 	{ tex : 'Omega', alias : ['Omega'] },        
	Theta		: 	{ tex : 'Theta', alias : ['Theta'] },               
	Pi			: 	{ tex : 'Pi', alias : ['Pi'] },                 
	Phi			: 	{ tex : 'Phi', alias : ['Phi']},

	// Binary operation 
	pm			:	{ tex : 'pm', alias : ['pm']},                  
	cap			:	{ tex : 'cap', alias : ['cap']},                
	diamond		:	{ tex : 'diamond', alias : ['diamond']},                    
	oplus		:	{ tex : 'oplus', alias : ['oplus']},      
	mp			:	{ tex : 'mp', alias : ['mp']},                  
	cup			:	{ tex : 'cup', alias : ['cup']},                
	bigtriangleup :	{ tex : 'bigtriangleup', alias : ['bigtriangleup']},              
	ominus		:	{ tex : 'ominus', alias : ['ominus']},     
	times		:	{ tex : 'times', alias : ['times']},               
	uplus		:	{ tex : 'uplus', alias : ['uplus']},              
	bigtriangledown :	{ tex : 'bigtriangledown', alias : ['bigtriangledown']},            
	otimes		:	{ tex : 'otimes', alias : ['otimes']},     
	div			:	{ tex : 'div', alias : ['div']},                 
	sqcap		:	{ tex : 'sqcap', alias : ['sqcap']},              
	triangleleft :	{ tex : 'triangleleft', alias : ['triangleleft']},               
	oslash		:	{ tex : 'oslash', alias : ['oslash']},     
	ast			:	{ tex : 'ast', alias : ['ast']},                 
	sqcup		:	{ tex : 'sqcup', alias : ['sqcup']},              
	triangleright :	{ tex : 'triangleright', alias : ['triangleright']},              
	odot		:	{ tex : 'odot', alias : ['odot']},       
	star		:	{ tex : 'star', alias : ['star']},                
	vee			:	{ tex : 'vee', alias : ['vee']},                
	'lhd$^b$'		:	{ tex : 'lhd$^b$', alias : ['lhd']},                    
	bigcirc		:	{ tex : 'bigcirc', alias : ['bigcirc']},    
	circ		:	{ tex : 'circ', alias : ['circ']},                
	wedge		:	{ tex : 'wedge', alias : ['wedge']},              
	'rhd$^b$'		:	{ tex : 'rhd$^b$', alias : ['rhd']},                    
	dagger		:	{ tex : 'dagger', alias : ['dagger']},     
	bullet		:	{ tex : 'bullet', alias : ['bullet']},              
	setminus	:	{ tex : 'setminus', alias : ['setminus']},           
	'unlhd$^b$'	:	{ tex : 'unlhd$^b$', alias : ['unlhd']},                  
	ddagger		:	{ tex : 'ddagger', alias : ['ddagger']},    
	cdot		:	{ tex : 'cdot', alias : ['cdot']},                
	wr			:	{ tex : 'wr', alias : ['wr']},                 
	'unrhd$^b$'	:	{ tex : 'unrhd$^b$', alias : ['unrhd']},                  
	amalg		:	{ tex : 'amalg', alias : ['amalg']},

	// Relation Symbols
	leq 		:	{ tex : 'leq', alias : ['leq']},                 
	geq 		:	{ tex : 'geq', alias : ['geq']},                
	equiv 		:	{ tex : 'equiv', alias : ['equiv']},              
	models 		:	{ tex : 'models', alias : ['models']},       
	prec 		:	{ tex : 'prec', alias : ['prec']},                
	succ 		:	{ tex : 'succ', alias : ['succ']},               
	sim 		:	{ tex : 'sim', alias : ['sim']},                
	perp 		:	{ tex : 'perp', alias : ['perp']},         
	preceq 		:	{ tex : 'preceq', alias : ['preceq']},              
	succeq 		:	{ tex : 'succeq', alias : ['succeq']},             
	simeq 		:	{ tex : 'simeq', alias : ['simeq']},              
	mid 		:	{ tex : 'mid', alias : ['mid']},          
	ll 			:	{ tex : 'll', alias : ['ll']},                  
	gg 			:	{ tex : 'gg', alias : ['gg']},                 
	asymp 		:	{ tex : 'asymp', alias : ['asymp']},              
	parallel 	:	{ tex : 'parallel', alias : ['parallel']},     
	subset 		:	{ tex : 'subset', alias : ['subset']},              
	supset 		:	{ tex : 'supset', alias : ['supset']},             
	approx 		:	{ tex : 'approx', alias : ['approx']},             
	bowtie 		:	{ tex : 'bowtie', alias : ['bowtie']},       
	subseteq 	:	{ tex : 'subseteq', alias : ['subseteq']},            
	supseteq 	:	{ tex : 'supseteq', alias : ['supseteq']},           
	cong 		:	{ tex : 'cong', alias : ['cong']},               
	'Join$^b$' 	:	{ tex : 'Join$^b$', alias : ['Join']},     
	'sqsubset$^b$' 		:	{ tex : 'sqsubset$^b$', alias : ['sqsubset']},        
	'sqsupset$^b$' 		:	{ tex : 'sqsupset$^b$', alias : ['sqsupset']},       
	neq 				:	{ tex : 'neq', alias : ['neq']},                
	smile 		:	{ tex : 'smile', alias : ['smile']},        
	sqsubseteq 	:	{ tex : 'sqsubseteq', alias : ['sqsubseteq']},          
	sqsupseteq 	:	{ tex : 'sqsupseteq', alias : ['sqsupseteq']},         
	doteq 		:	{ tex : 'doteq', alias : ['doteq']},              
	frown 		:	{ tex : 'frown', alias : ['frown']},        
	in 			:	{ tex : 'in', alias : ['in']},                  
	ni 			:	{ tex : 'ni', alias : ['ni']},                 
	propto 		:	{ tex : 'propto', alias : ['propto']},             
	vdash 		:	{ tex : 'vdash', alias : ['vdash']},               
	dashv 		:	{ tex : 'dashv', alias : ['dashv']},


	leftarrow 		:	{ tex : 'leftarrow', alias : ['leftarrow']},                    
	longleftarrow 	:	{ tex : 'longleftarrow', alias : ['longleftarrow']},               
	uparrow 		:	{ tex : 'uparrow', alias : ['uparrow']},       
	Leftarrow 		:	{ tex : 'Leftarrow', alias : ['Leftarrow']},                    
	Longleftarrow 	:	{ tex : 'Longleftarrow', alias : ['Longleftarrow']},               
	Uparrow 		:	{ tex : 'Uparrow', alias : ['Uparrow']},       
	rightarrow 		:	{ tex : 'rightarrow', alias : ['rightarrow']},                   
	longrightarrow 	:	{ tex : 'longrightarrow', alias : ['longrightarrow']},              
	downarrow 		:	{ tex : 'downarrow', alias : ['downarrow']},     
	Rightarrow 		:	{ tex : 'Rightarrow', alias : ['Rightarrow']},                   
	Longrightarrow 	:	{ tex : 'Longrightarrow', alias : ['Longrightarrow']},              
	Downarrow 		:	{ tex : 'Downarrow', alias : ['Downarrow']},     
	leftrightarrow 	:	{ tex : 'leftrightarrow', alias : ['leftrightarrow']},               
	longleftrightarrow 		:	{ tex : 'longleftrightarrow', alias : ['longleftrightarrow']},          
	updownarrow 	:	{ tex : 'updownarrow', alias : ['updownarrow']},   
	Leftrightarrow 	:	{ tex : 'Leftrightarrow', alias : ['Leftrightarrow']},               
	Longleftrightarrow 		:	{ tex : 'Longleftrightarrow', alias : ['Longleftrightarrow']},          
	Updownarrow 		:	{ tex : 'Updownarrow', alias : ['Updownarrow']},   
	mapsto 			:	{ tex : 'mapsto', alias : ['mapsto']},                       
	longmapsto 		:	{ tex : 'longmapsto', alias : ['longmapsto']},                  
	nearrow 		:	{ tex : 'nearrow', alias : ['nearrow']},       
	hookleftarrow 	:	{ tex : 'hookleftarrow', alias : ['hookleftarrow']},                
	hookrightarrow 	:	{ tex : 'hookrightarrow', alias : ['hookrightarrow']},              
	searrow 		:	{ tex : 'searrow', alias : ['searrow']},       
	leftharpoonup 	:	{ tex : 'leftharpoonup', alias : ['leftharpoonup']},                
	rightharpoonup 	:	{ tex : 'rightharpoonup', alias : ['rightharpoonup']},              
	swarrow 		:	{ tex : 'swarrow', alias : ['swarrow']},       
	leftharpoondown :	{ tex : 'leftharpoondown', alias : ['leftharpoondown']},              
	rightharpoondown 	:	{ tex : 'rightharpoondown', alias : ['rightharpoondown']},            
	nwarrow 		:	{ tex : 'nwarrow', alias : ['nwarrow']},       
	rightleftharpoons 		:	{ tex : 'rightleftharpoons', alias : ['rightleftharpoons']},            
	'leadsto$^b$' 	:	{ tex : 'leadsto$^b$', alias : ['leadsto$^b$']},        
 


};